### PR TITLE
add pytraj to readme

### PR DESCRIPTION
**Pull request by spackman**
pytraj is a python front-end for AmberTools cpptraj utility. This program is used for analysis of MD trajectories and features interfaces to numpy, scipy, pandas and sklearn.

### CODE REVIEW

**Comment by lmmentel** [comment]
Thanks for the contribution. It seems that this project might be a bit stale. Last release was in 2020 and [code frequency](https://github.com/Amber-MD/pytraj/graphs/code-frequency) does not show a lot of activity.

**Comment by spackman** [comment]
You are correct- this is older code. I updated the link to connect directly to the repo instead of the docs.

**Comment by lmmentel** [comment]
I'm not convinced about adding this package since it seems unmaintained.

**Comment by spackman** [comment]
That appears accurate. I included it as I have found it useful in my own research.

**Comment by lmmentel** [comment]
Closing, without merging since package seems unmaintained. Feel free to reopen if you have suggestions on how to make it clear it's unmaintained.

**Pull request closed without merging**
