### PR TITLE
Add datamol

### PR DESCRIPTION
**Pull request by hadim**

### CODE REVIEW

**Comment by hadim** [comment]
ping @lmmentel

**Comment by lmmentel** [comment]
HI @hadim, thanks for the contribution. The items in the list are in the alphabetical order, could you update the PR to conform to that? Thanks!

**Comment by hadim** [comment]
Sorry I missed that. Done now.

**Comment by hadim** [comment]
ahah my bad.

**Comment by lmmentel** [comment]
Great, thanks a lot for suggesting datamol it looks really interesting.

**Pull request merged**
