### PR TITLE
1. Adding AQME and ROBERT

### PR DESCRIPTION
**Pull request by ddgunizar**

### CODE REVIEW

**Comment by ddgunizar** [comment]
Hi! First of all thank you for your work, it is a great help! I send you this PR to incorporate 2 programs from our group. AQME for the automation of QM calculations and ROBERT for machine learning. There are awesome because they automate many protocols for non-expert users.

**Comment by lmmentel** [comment]
Thank you for the additions. Could you add linki to githib instead of the docs?

**Comment by ddgunizar** [comment]
Done

**Review by lmmentel — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
